config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  root 'pages#home'
  get "login" => "pages#login"
  get "signup" => "pages#signup"
  get "step2" => "pages#step2"
  get "advisors" => "pages#advisors"
  get "students" => "pages#students"
  get "student" => "pages#student"
  get "advisor" => "pages#advisor"
  

end

app/models/user.rb
# Schema
# 	  add_column :users, :name, :string
# 	  add_column :users, :mini_bio, :string
#     add_column :users, :nationality, :string
#     add_column :users, :latest_position, :string
#     add_column :users, :university, :string
#     add_column :users, :experience, :text


class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  after_create :set_guid

  def set_guid
		self.guid = SecureRandom.uuid()
		self.save
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to users_path
    end
  end
  def login
  end
  def signup
  end
  def step2
  end
  def advisors
  end
  def students
  end
  def student
  end
  def advisor
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :email, :password)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :current_password, :mini_bio, :country, :latest_position, :university, :experience)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show]
	def index
		@users = User.all
	end

	def show
	end

	private

	def set_user
		@user = User.find_by(guid: params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
      <!-- main-footer -->
      <footer class="main-footer">


        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <ul class="list-inline link-footer text-center-xs">
                <li><a href="index.html">Home</a></li>
                <li><a href="blog.html">Blog</a></li>
                <li><a href="about.html">About Us</a></li>
                <li><a href="contact.html">Contact Us</a></li>
              </ul>
            </div>
            <div class="col-sm-6 ">
              <p class="text-center-xs hidden-lg hidden-md hidden-sm">Stay Connect</p>
              <div class="socials text-right text-center-xs">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-youtube-play"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
      </footer><!-- end main-footer -->

app/views/layouts/_nav.html.erb
<!-- main navbar -->
        <nav class="navbar navbar-default main-navbar hidden-sm hidden-xs">
          <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav">
              <li class=""><%= link_to "<i class='fa fa-university'></i> connective".html_safe, root_path, class: "font-bold" %></li>
                <li class=""><%= link_to users_path do %><strong>Advisors</strong><% end %></li>
                <li class=""><%= link_to users_path do %><strong>Students</strong><% end %></li>
              </ul>      
              <ul class="nav navbar-nav navbar-right">
              <% unless current_user %>
                
                <li class="link-btn"><%= link_to new_user_session_path do %><span class="btn btn-theme btn-pill btn-xs btn-line">Login</span><% end %></li>
                <li class="link-btn"><%= link_to new_user_registration_path do %><span class="btn btn-theme  btn-pill btn-xs btn-line">Signup</span><% end %></li>
                <% else %>
                <li class="dropdown">
                  <a href="#" class="link-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-user"></i> &nbsp; <%= current_user.name %> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Public Profile", user_path(current_user.guid) %></li>
                    <li><a href="change_password.html"> Call Center</a></li>
                    <li><%= link_to "Settings", edit_user_registration_path %></li>
                  </ul>
                </li>
<li class="link-btn"><%= link_to destroy_user_session_path, method: :delete do %><span class="btn btn-theme  btn-pill btn-xs btn-line">Logout</span><% end %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav><!-- end main navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connective</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="wrapper">
 <%= render "layouts/nav" %>
<%= yield %>
<%= render "layouts/footer" %>
</div>
</body>
</html>

app/views/pages/advisor.html.erb
<div class="wrapper">
      <!-- main-header -->
      <header class="main-header">
      <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="logo text-center-sm inline"> <a href="index.html">
              <%= image_tag "logo.png" %>
                  <div class="label-add">Mentors</div>
                </a>
              </div>
            </div>
            <div class="col-md-8">

              <!-- form search  -->
              <form class="form-search-list">
                <div class="row">
                  <div class="col-sm-5 col-xs-6">
                    <div class="form-group">
                      <label class="color-white">What</label>
                      <input class="form-control" placeholder="job title, skill or company name" >
                    </div>
                  </div>
                  <div class="col-sm-5 col-xs-6">
                    <div class="form-group">
                      <label class="color-white">Where</label>
                      <input class="form-control" placeholder="city, province, or region">
                    </div>
                  </div>
                  <div class="col-sm-2 col-xs-12">
                    <div class="form-group">
                      <label class="hidden-xs">&nbsp;</label>
                      <button class="btn btn-block btn-theme  btn-success">Search</button>
                    </div>
                  </div>
                </div>
                <p class="text-right"><a  href="#modal-advanced" data-toggle="modal" class="link-white">Advanced Search</a></p>
              </form><!-- end form search  -->


            </div>
          </div>
      </header>
         <!-- body-content -->
      <div class="body-content clearfix" >

        <!-- link top -->
        <div class="bg-color2 block-section-xs line-bottom">
          <div class="container">
            <div class="row">
              <div class="col-sm-6 hidden-xs">
                <div>Resume details :</div>
              </div>
              <div class="col-sm-6">
                <div class="text-right"><a href="#">&laquo; Go back to resume listings</a></div>
              </div>
            </div>
          </div>
        </div><!-- end link top -->

        <div class="bg-color2">
          <div class="container">
            <div class="row">
              <div class="col-md-9">

                <!-- box item details -->
                <div class="block-section box-item-details">
                  <div class="resume-block">
                    <div class="img-profile"><img src="./assets/theme/images/people/7.jpg" alt=""></div>
                    <div class="desc">
                      <h2>Bryon Czoch</h2>
                      <h4>PHP Developer</h4>
                      <p>Chicago, IL</p>

                      <h3 class="resume-sub-title"><span>Work Experience</span></h3>

                      <h4>PHP Developer</h4>
                      <h5>Barcode Giant <span class="color-white-mute"> - Chicago, IL</span></h5>
                      <p  class="color-white-mute">March 2014 to August 2014</p>
                      <h5>Responsibilities :</h5>
                      <p>Magento/PHP development for a Point-of-sale equiptment dealer. I worked on setting up VMware ESX sandbox developer environment. I also built their quote system in Magento. They have 8 other websites that sell the same equipment so I also worked on keeping them up to date with the main website that brings in revenue. </p>
                      <h5>Skills Used :</h5>
                      <p>PHP, Javascript, XML, JSON, Linux Apache Mysql and Python</p>


                      <h4>Programmer/Analyst II</h4>
                      <h5>University of Chicago</h5>
                      <p class="color-white-mute">March 2012 to March 2014</p>
                      <p>Extending/Customizing Zend Framework 2 based library search resource portal (http://myportal.domain.com) 
                        <br/>Maintaining legacy employee travel/training requisition system and division hours site</p>

                      <h4>Web Developer/System Administrator</h4>
                      <h5>American Nuclear Society</h5>
                      <p  class="color-white-mute">March 2011 to March 2012</p>
                      <p>Programming additions to the existing Ans.org website </p>
                      <ul>
                        <li>Supporting/migrating Wordpress blog AnsNuclearCafe.org </li>
                        <li>Setup, support of Linux servers</li>
                        <li>Supporting operations of the organization w/ tech knowledge </li>
                      </ul>


                      <h3 class="resume-sub-title"><span>Education</span></h3>
                      <h4>Bachelor in Computer Science</h4>
                      <h5>Telkom University <span class="color-white-mute">- Bloomington, IN</span></h5>

                      <h3  class="resume-sub-title"><span>Additional Information</span></h3>
                      <h4>SKILLS:</h4>
                      <ul>
                        <li> PHP 5, Perl and Python scripting </li>
                        <li>Java</li>
                        <li>SQL, Mysql, MongoDB </li>
                        <li>Revision control/source code management using Mercurial, GIT, RCS/CVS </li>
                        <li>JavaScript Libraries</li>
                        <li>Apache Solr search engine </li>
                        <li>Wordpress, Drupal, Joomla, Mambo, CMS </li>
                        <li>Adobe Photoshop & GIMP </li>
                        <li> Working in a Linux / Unix environment (shell scripting and command line utilities)</li>
                      </ul>
                    </div>
                  </div>
                </div><!-- end box item details -->


              </div>
              <div class="col-md-3">

                <!-- box affix right -->
                <div class="block-section " id="affix-box">
                  <div class="text-right">
                    <p><a href="#" class="btn btn-theme btn-line dark btn-block-xs">Make Call Request</a></p>
                    <p>Last call 3 days Ago</p>
                   
                  </div>
                </div><!-- box affix right -->

              </div>
            </div>
          </div>
        </div>


      </div><!--end body-content -->


</div>

app/views/pages/advisors.html.erb
<div class="wrapper">
      <!-- main-header -->
      <header class="main-header">
        <!-- form search area-->
        <div class="container">
          <div class="row">

            <div class="col-md-4">
              <!-- logo -->

              <div class="logo text-center-sm"> <a href="index.html"><%= image_tag "logo.png" %></a></div>
              
            </div>

            <div class="col-md-8">
              <!-- form search -->
              <form class="form-search-list">
                <div class="row">
                  <div class="col-sm-5 col-xs-6 ">
                    <div class="form-group">
                      <label class="color-white">Who</label>
                      <input class="form-control" placeholder="job title, keywords or hotel name" >
                    </div>
                  </div>
                  <div class="col-sm-5 col-xs-6 ">
                    <div class="form-group">
                      <label class="color-white">What</label>
                      <input class="form-control" placeholder="category, skill">
                    </div>
                  </div>
                  <div class="col-sm-2 col-xs-12 ">
                    <div class="form-group">
                      <label class="hidden-xs">&nbsp;</label>
                      <button class="btn btn-block btn-theme  btn-success">Search</button>
                    </div>
                  </div>
                </div>
              </form>  <!-- form search -->
            </div>


          </div>


        </div>
        </header>
       


      <!-- body-content -->
      <div class="body-content clearfix" >

        <div class="bg-color2">
          <div class="container">
            <div class="row">
              <div class="col-md-9">

                <!-- box listing -->
                <div class="block-section-sm box-list-area">

                  <!-- desc top -->
                  <div class="row hidden-xs">
                    <div class="col-sm-6  ">
                      <p><strong class="color-black">All Mentors</strong></p>
                    </div>
                    <div class="col-sm-6">
                      <p class="text-right">
                        Mentors 1 to 10 of 578
                      </p>
                    </div>
                  </div><!-- end desc top -->

                  <!-- item list -->  
                  <div class="box-list">
                    <div class="item">
                      <div class="row">
                        <div class="col-md-1 hidden-sm hidden-xs"><div class="img-item"><img src="./assets/theme/images/company-logo/1.jpg" alt=""></div></div>
                        <div class="col-md-11">
                          <h3 class="no-margin-top"><%= link_to advisor_path do %>Backend Developer <i class="fa fa-link color-white-mute font-1x"></i><% end %></h3>
                          <h5><span class="color-black">CollegeHumor</span> - <span class="color-white-mute">New York, NY 10011 (Chelsea area)</span></h5>
                          <p class="text-truncate ">Back-end development experience in PHP 5, and a strong understanding of Object Oriented Programming within an MVC framework</p>
                          <div>
                            <span class="color-white-mute">16 hours ago</span> - 
                            <a href="#need-login" data-toggle="modal" class="btn btn-xs btn-theme btn-default">save job</a> - 
                            <a href="#modal-email" data-toggle="modal"  class="btn btn-theme btn-xs btn-default">email</a> - 
                            <a href="#" class="btn btn-theme btn-xs btn-default">more ...</a>
                          </div>
                        </div>
                      </div>
                    </div><!-- end item list -->

                   


                  </div>



                  <!-- pagination -->
                  <nav >
                    <ul class="pagination pagination-theme  no-margin">
                      <li>
                        <a href="#" aria-label="Previous">
                          <span aria-hidden="true">&larr;</span>
                        </a>
                      </li>
                      <li class="active"><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><span>...</span></li>
                      <li><a href="#">50</a></li>
                      <li>
                        <a href="#" aria-label="Next">
                          <span aria-hidden="true">&rarr;</span>
                        </a>
                      </li>
                    </ul>
                  </nav><!-- pagination -->

                </div><!-- end box listing -->


              </div>
              <div class="col-md-3">
                <div class="block-section-sm side-right">
                  <div class="row">
                    <div class="col-xs-6">
                      <p><strong>Sort by: </strong></p>
                    </div>
                    <div class="col-xs-6">
                      <p class="text-right">
                        <strong>Relevance</strong> - <a href="#" class="link-black"><strong>Date</strong></a>
                      </p>
                    </div>
                  </div>

                  <div class="result-filter">
                    <h5 class="no-margin-top font-bold margin-b-20 " ><a href="#s_collapse_1" data-toggle="collapse" >Price <i class="fa ic-arrow-toogle fa-angle-right pull-right"></i> </a></h5>
                    <div class="collapse in" id="s_collapse_1">
                      <div class="list-area">
                        <ul class="list-unstyled">
                          <li>
                            <a  href="#" >$50,000+</a> (16947)
                          </li>
                          <li>
                            <a  href="#" >$70,000+</a> (13915)
                          </li>
                          <li>
                            <a  href="#" >$90,000+</a> (9398)
                          </li>
                          <li>
                            <a  href="#" >$110,000+</a> (4112)
                          </li>
                          <li>
                            <a  href="#" >$130,000+</a> (1864)
                          </li>
                        </ul>
                      </div>
                    </div>

                    <h5 class="font-bold  margin-b-20" ><a href="#s_collapse_5" data-toggle="collapse" >Position <i class="fa ic-arrow-toogle fa-angle-right pull-right"></i></a> </h5>
                    <div class="collapse in" id='s_collapse_5'>
                      <div class="list-area">
                        <ul class="list-unstyled ">
                          <li>
                            <a  href="#" >Full-time </a> (558)
                          </li>
                          <li>
                            <a  href="#" >Part-time </a> (438)
                          </li>
                          <li>
                            <a  href="#" >Contract </a> (313)
                          </li>
                          <li>
                            <a  href="#" >Internship</a> (169)
                          </li>
                          <li>
                            <a  href="#" >Temporary  </a> (156)
                          </li>
                        </ul>

                      </div>
                    </div>


                    <h5 class="font-bold  margin-b-20"><a href="#s_collapse_2" data-toggle="collapse" >Segment <i class="fa ic-arrow-toogle fa-angle-right pull-right"></i></a>  </h5>
                    <div class="collapse in" id="s_collapse_2">
                      <div class="list-area">
                        <ul class="list-unstyled ">
                          <li>
                            <a  href="#" >web developer</a> (558)
                          </li>
                          <li>
                            <a  href="#" >PHP Developer</a> (438)
                          </li>
                          <li>
                            <a  href="#" >Software Engineer </a> (313)
                          </li>
                          <li>
                            <a  href="#" >Senior Software Engineer </a> (169)
                          </li>
                          <li>
                            <a  href="#" >Front End Developer </a> (156)
                          </li>
                          <li>
                            <a  href="#" >More ... </a> 
                          </li>
                        </ul>

                      </div>
                    </div>


                    <h5 class="font-bold  margin-b-20"><a href="#s_collapse_3" data-toggle="collapse" >Chain <i class="fa ic-arrow-toogle fa-angle-right pull-right"></i></a> </h5>
                    <div class="collapse in" id="s_collapse_3">
                      <div class="list-area">
                        <ul class="list-unstyled ">
                          <li>
                            <a  href="#" >Unlisted Company</a> (558)
                          </li>
                          <li>
                            <a  href="#" >CyberCoders</a> (438)
                          </li>
                          <li>
                            <a  href="#" >Smith & Keller </a> (313)
                          </li>
                          <li>
                            <a  href="#" >Robert Half Technology </a> (169)
                          </li>
                          <li>
                            <a  href="#" >Jobspring Partners </a> (156)
                          </li>
                          <li>
                            <a  href="#" >More ... </a> 
                          </li>
                        </ul>

                      </div>
                    </div>


                    <h5 class="font-bold  margin-b-20" ><a href="#s_collapse_4" data-toggle="collapse" class="collapsed" >Location  <i class="fa ic-arrow-toogle fa-angle-right pull-right"></i> </a></h5>
                    <div class="collapse" id='s_collapse_4'>
                      <div class="list-area">
                        <ul class="list-unstyled ">
                          <li>
                            <a  href="#" >New York, NY </a> (558)
                          </li>
                          <li>
                            <a  href="#" >San Francisco, CA </a> (438)
                          </li>
                          <li>
                            <a  href="#" >Washington, DC </a> (313)
                          </li>
                          <li>
                            <a  href="#" >Chicago, IL</a> (169)
                          </li>
                          <li>
                            <a  href="#" >Austin, TX  </a> (156)
                          </li>
                          <li>
                            <a  href="#" >More ... </a> 
                          </li>
                        </ul>

                      </div>
                    </div>





                  </div>
                </div>


              </div>
            </div>
          </div>
        </div>



        <!-- modal need login -->
        <div class="modal fade" id="need-login">
          <div class="modal-dialog modal-md">
            <div class="modal-content">

              <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" >You must login to save jobs</h4>
              </div>
              <div class="modal-footer text-center">
                <a href="#" class="btn btn-default btn-theme" >Login</a>
                <a href="#" class="btn btn-success btn-theme">Create account (it's free)</a>
              </div>

            </div>
          </div>
        </div><!-- end modal  need login -->


        <!-- modal need login -->
        <div class="modal fade" id="modal-email">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <form>
                <div class="modal-header ">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" >Send this job to yourself or a friend:</h4>
                </div>
                <div class="modal-body">
                  <div class="form-group">
                    <label>From my email address</label>
                    <input type="email" class="form-control "  placeholder="Enter Email">
                  </div>
                  <div class="form-group">
                    <label>To email address</label>
                    <input type="email" class="form-control "  placeholder="Enter Email">
                  </div>

                  <div class="form-group">
                    <label>Comment (optional)</label>
                    <textarea class="form-control" rows="6" placeholder="Something Comment"></textarea>
                  </div>
                  <div class="checkbox flat-checkbox">
                    <label>
                      <input type="checkbox"> 
                      <span class="fa fa-check"></span>
                      Send a copy to my email address?
                    </label>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default btn-theme" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-success btn-theme">Send</button>
                </div>
              </form>
            </div>
          </div>
        </div><!-- end modal  need login -->        
      </div><!--end body-content -->
       </div>

app/views/pages/login.html.erb
<!-- body-content -->
      <div class="body-content clearfix" >

        <div class="block-section bg-color4">
            <div class="text-center logo"> <a href="index.html"><%= image_tag "logo.png" %></a></div>
  <br>
          <div class="container">
            <div class="panel panel-md">
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-12">
             
                    <!-- form login -->
                    <form>
                   
                      <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" placeholder="Your Email">
                      </div>
                      <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Your Password">
                      </div>
                      <div class="white-space-10"></div>
                      <div class="form-group no-margin">
                        <button class="btn btn-theme btn-lg btn-t-primary btn-block">Login</button>
                      </div>
                    </form><!-- form login -->

                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>

     

      </div><!--end body-content -->

app/views/pages/signup.html.erb
<!-- body-content -->
      <div class="body-content clearfix" >

        <div class="block-section bg-color4">

          <div class="container">

  <div class="text-center logo"> <a href="index.html"><%= image_tag "logo.png" %></a></div>
  <br>
            <div class="panel panel-md">
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-12">
             
                    <!-- form login -->
                    <form>
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" placeholder="Your Name">
                      </div>
                      <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" placeholder="Your Email">
                      </div>
                      <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Your Password">
                      </div>
                      <div class="white-space-10"></div>
                      <div class="form-group no-margin">
                      <%= link_to "Signup", step2_path, class: "btn btn-theme btn-lg btn-t-primary btn-block" %>
                      </div>
                    </form><!-- form login -->

                  </div>
                </div>
              </div>
            </div>

            <div class="white-space-20"></div>
            <div class="text-center color-white">By creating an account, you agree to Connective <br/><a href="#" class="link-white"><strong>Terms of Service</strong></a> and consent to our <a href="#" class="link-white"><strong>Privacy Policy</strong></a>.</div>
          </div>
        </div>

        <div class="block-section bg-color2">
          <div class="container text-center">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <i class="fa fa-question fa-5x box-icon"></i>
                <h2 class=""> Why create an account?</h2>
                <hr/>
                <p><i class="fa fa-check"></i> Manage, create and delete your job alerts</p>
                <p><i class="fa fa-check"></i> Access your saved jobs and notes from any computer</p>

              </div>
            </div>
          </div>
        </div>

      </div><!--end body-content -->

app/views/users/_user.html.erb
   <!-- item listing  -->
                    <div class="item">
                      <div class="row">
                        <div class="col-md-1 hidden-sm hidden-xs"><div class="img-item">
<%= gravatar_tag user.email, :size => 30 %>
                        </div></div>
                        <div class="col-md-11">
                          <h3 class="no-margin-top"><%= link_to user_path(user.guid) do %><%= user.name %>  <i class="fa fa-link color-white-mute font-1x"></i><% end %></h3>
                          <h5><span class="color-black"><%= user.country %></span></h5>
                          <p><%= user.latest_position %> </span> <br/>
                            <span class="color-white-mute"><%= user.university %></span></p>
                          <div>
                            <span class="color-white-mute">Member since <%= time_ago_in_words(user.created_at) %> ago</span>
                            
                            <%= link_to "More", user_path(user.guid), class: "btn btn-xs btn-theme btn-default" %>
                          </div>
                        </div>
                      </div>
                    </div><!-- end item listing  -->